name: disign
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1 
  get: ^4.6.6
  shared_preferences: ^2.2.3 
  flutter: 
    sdk: flutter
  path_provider: ^2.1.3 
  basic_utils: ^5.5.4 
  syncfusion_flutter_pdf: ^26.1.3 
  file_picker: ^8.0.0+1
  intl: ^0.19.0 
  pin_code_fields: ^8.0.1 
  crypto: ^3.0.3 
  flutter_pw_validator: ^1.5.0 
  permission_handler: ^11.1.0 
  share_plus: 11.0.0 
  flutter_slidable: ^3.0.1 
  pointycastle: ^3.7.3 
  flutter_secure_storage: ^9.0.0 
  device_info_plus: 10.1.2
  open_file: ^3.5.10
  
  


dev_dependencies: 
  flutter_lints: ^3.0.1 
  lints: ^3.0.0 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/